### ISSUE TITLE
Allow T-s value pairs for definition of fluid states 

### ISSUE THREAD

**Issue by spinnau** [ibell/coolprop#117]
It would be great, if Props and State classes could be instantiated with T-s value pairs.

In Python I use a Newton-Raphson solver from scipy to calculate the pressure and then define the state with p-s value pair. With p_triple as an initial guess this works without problems for liquid, gas and two-phase states. 

``` python
from CoolProp.CoolProp import Props
from CoolProp.State import State
from scipy.optimize import newton

fluid = 'Water'
T = 573.15
s = 8.2

p_guess = Props(fluid, 'ptriple')
p = newton(lambda p_i: Props('T', 'P', p_i, 'S', s, fluid)-T, x0=p_guess)
S = State(fluid, dict(P=p, S=s))
```

For easier usage also in other supported languages/environments it would be nice to have this implemented as an internal function in CoolProp.

I have created a working proposal for implementation in 2d257001837de2eb which works the same way as the above python solution. Any ideas or comments on this?

**Comment by ibell** [comment]
I like your idea, but I can see two problems:
- If T, s is two-phase, your method will fail because T,P are not unique in two-phase region.  It would be better to iterate on density I think with temperature held constant.  That way it is only a 1-D iteration.  And T,D is the natural pair of inputs for the EOS, so you can't do any faster.
- This method is going to be SLOW since you are iterating on an inner loop that is a P,S iteration, which is itself also slow.  This is not fast enough for integration into the main codebase I don't think.

In any case, I agree it would be great to have T,S as inputs.  Let's make this happen!

By the way, where is that commit?  Is it in some weird branch?  It's not in master, and I don't see a new branch that you have added.

**Comment by ibell** [comment]
See also #118

**Comment by spinnau** [comment]
@ibell That commit is in my forked repo in the _Ts_solver_ branch. I don't know why GitHub shows the commit in _ibell/coolprop_ repo after clicking the link.

The proposed implementation works even if T,s is two-phase, because `T(p,s) - T = 0` is solved for the pressure and the fluid is instantiated with the unique p,s pair afterwards.

To avoid the slow p,s-iteration, I have changed the code to solve `s(T,rho) - s = 0` for the density with the given T,s pair by using the `Fluid::entropy_Trho` function internally. Afterward the fluid is instantiated with the T,rho pair. But I get wrong values in liquid and two-phase regions. 

Using this algorithm in python with scipy.optimize.newton works fine for all regions.  

``` python
from CoolProp.CoolProp import Props
from CoolProp.State import State
from scipy.optimize import newton

fluid = 'Water'
T = 573.15
s = 8.2

rho = newton(lambda rho_i: Props('S', 'T', T, 'D', rho_i, fluid)-s, x0=0.1)
S = State(fluid, dict(T=T, D=rho))
```

**Comment by spinnau** [comment]
I have changed the initial density values for the iteration (3a4f3eedac29ee600224). Now it works for liquid, two-phase and gas regions.

**Comment by spinnau** [comment]
@ibell Now the ancillary equations will be used for first phase check. Thanks for your hints on that. Please see f3297e9dd5ceeb8051bc79c968ab698cd3827c5d for the changes.
