### ISSUE TITLE
Restoring some of the plotting functionality

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#18]
I suppose I was a bit too hasty in my merge of the new plotting code, but there were some quite significant non-backwards-compatible changes made, and some of the changes I would like to see reverted.  

For one, I am not sure how anything works in the import of CoolProp.Plots since the **init**.py file references Plots.Ts, Plots.ph, etc.  I would like to see those functions restored as they are very convenient for simple things and that is a pretty major API change.

I suspect we will run into some other problems as well.

That said I really appreciate your help, and the plotting functionality for more advanced plots has been greatly improved.

**Comment by jowr** [comment]
How about including the new code as CoolProp.Plots2? That allows everyone to test the new functionality and does not break the API. We can then mature the code together and replace CoolProp.Plots in the next release. We might also provide some wrapper functions to maintain backward compatibility.

ibell notifications@github.com wrote:

I suppose I was a bit too hasty in my merge of the new plotting code, but there were some quite significant non-backwards-compatible changes made, and some of the changes I would like to see reverted.

For one, I am not sure how anything works in the import of CoolProp.Plots since the init.py file references Plots.Ts, Plots.ph, etc. I would like to see those functions restored as they are very convenient for simple things and that is a pretty major API change.

I suspect we will run into some other problems as well.

That said I really appreciate your help, and the plotting functionality for more advanced plots has been greatly improved.

**Comment by lgpage** [comment]
There are a few possible options we can take:
1) revert the merge of python_plots into the master branch and keep the new code on a separate branch until we iron out the functionality and bugs (well documented in http://git-scm.com/blog/2010/03/02/undoing-merges.html)
2) keep the code as is and add wrapper functions to keep current functionality
3) create a completely stand-alone version of the new code in Plots2

My preference is for option 1 or 2.

As a side note I hadn't actually looked at the code in the init.py file, but adding wrappers to the current code to maintain the current functionality is quite easy.

Let me know your preferences, in the mean time I'll start working on the wrapper functions to at least be able to maintain backwards compatibility for a few future releases.

**Comment by ibell** [comment]
Now that I have merged both the unit-handling code and the plots, the
easiest would be to just write the wrapper functions for backwards
compatibility.  So I propose we do that.  Do you want to do this, or should
I?

**Comment by lgpage** [comment]
I'll get right on this.

**Comment by ibell** [comment]
Much obliged, I'm a bit stuck for the moment since I have a lot of code
that is dependent on the ph and Ts plots in particular.  Though it would be
nice to put back all the others as well.

**Comment by lgpage** [comment]
I've added wrapper functions for the Ts and Ph plots for now.
I will work on added all the others as well as the drawIsoLines functionality.

**Comment by ibell** [comment]
Ok, fixed to my satisfaction in revision fd95705bbb4be2d548dafafda3a9bc07588d9086
