### ISSUE TITLE
Bug with R245fa conductivity

### ISSUE THREAD

**Issue by evinvodkha** [ibell/coolprop#255]
Hi,

Using Coolprop 5.0.8 in Python, the following line raises an exception :
cp.PropsSI('L','P',5e5,'T',373,'R245fa')

saying:
ValueError: Conformal state solver failed; error was _phase is unknown : PropsSI("L","P",500000,"T",373,"R245fa")

However the line:
cp.PropsSI('L','P',5e5,'T',373,'REFPROP-R245fa')
works fine, giving result 0.0193013951388472

Any idea?

Thanks for the great work !

Thomas.

**Comment by jowr** [comment]
Have you checked where the phase boundary is? CoolProp tells you that it 
does not know the phase. REFPROP might do something special 
(interpolation?) in the two-phase region. This is disabled by default in 
CoolProp because there are many different ways to interpolate and we 
want the user to be aware of the problem.

**Comment by ibell** [comment]
Please file new bugs at https://github.com/CoolProp/CoolProp/issues, these
are for v4

**Comment by jowr** [comment]
Yes, continue here: https://github.com/CoolProp/CoolProp/issues/604

**Comment by evinvodkha** [comment]
sorry, not too familiar with Github ;). Thanks for the answer
