### ISSUE TITLE
processing vector of inputs within Matlab

### ISSUE THREAD

**Issue by witmb** [ibell/coolprop#266]
Hi,

Is it possible to process vectors of e.g. pressures and temperatures for a certain fluid at once instead of via a for loop going over all the pressure-temperature combination one by one? I'm using Matlab.

Thanks for your help!

Maarten

**Comment by jowr** [comment]
If you calculate different states, there is not much of a benefit passing vectors instead of creating an outer loop. The costly function is the update the state and that cannot be avoided. You can use an output vector to get several quantities at the same state, but that is not what you want. 

By the way, this is the old repository, you should go to https://github.com/CoolProp/CoolProp
