### ISSUE TITLE
makefile or instructions for building c++ libraries using gcc on linux

### ISSUE THREAD

**Issue by Rod-Persky** [ibell/coolprop#37]
It is fairly straight forward to use the build scripts for most environments, however it would be helpful to get a script for building the CoolProp library files for importing into C++ programs.

**Comment by ibell** [comment]
Do you want a static library (you probably do)?  If so, check out the build
script in the wrappers/StaticLibrary folder.  I can bake one for GCC as
well.  You have to make sure that CoolProp and your software are compiled
with the same runtime libraries, which is why I build four versions of the
static library for visual studio.

Ian

**Comment by Rod-Persky** [comment]
I have a small makefile working, this is tested against a small program that simply gets the fluid index from the library. The makefile generates a shared library (.so) rather than a static library (.a),  that's the only way I've used library up to now.

The makefile (the make command) needs to be run in the CoolProp source directory where make builds libCoolProp.so.3.3.0 and sudo make install copies it to places relevent to archlinux.

``` makefile
CC=g++

MAJOR=3
MINOR=3
REVISON=0
LIBDIR=/usr/lib
BASENAME=libCoolProp.so
EXECUTABLE=$(BASENAME).$(MAJOR).$(MINOR).$(REVISON)

CFLAGS=-O0 -g -fPIC -c -Wall -I$(shell pwd)
LDFLAGS=-shared -ldl -Wl,-soname,$(EXECUTABLE)

SOURCES=$(shell echo *.cpp)
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS) 
    $(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
    $(CC) $(CFLAGS) $< -o $@

clean:
    echo $(VERSION)
    rm -rf *.o $(EXECUTABLE)

install:
    mkdir -p -m 655 /usr/include/CoolProp
    install -c $(EXECUTABLE) $(LIBDIR)
    ln -sf $(LIBDIR)/$(EXECUTABLE) /usr/include/$(BASENAME)
    ln -sf $(LIBDIR)/$(EXECUTABLE) /usr/include/CoolProp/$(BASENAME)
    ldconfig
    cp -Rn . /usr/include/CoolProp
    find /usr/include/CoolProp ! -name "*.h" -delete

uninstall:
    rm -rf $(LIBDIR)/$(EXECUTABLE)
    rm -rf /usr/include/CoolProp
    rm -rf /usr/include/$(BASENAME)
```

**Comment by ibell** [comment]
Hi Rod, that is really nice!  What would maybe improve it would be if you could provide the path to the source files directly so that we could put it in a wrappers/Linux folder or something like that.  @jowr what do you think?  Also it would be great if you could use a compiled (python?) version of CoolProp to pull the version number rather than hardcoding it.  Apart from that, looks good.  I can make you a contributor so you can add it to the codebase.

**Comment by jowr** [comment]
Yes, it looks good. Rod, maybe you can get some more inspiration from this file:
https://github.com/ibell/coolprop/blob/master/wrappers/Modelica/makefile

It is the makefile I use for building a library for Modelica and I reckon that the build process for C++ should be very similar. Unfortunately, I also miss a smart solution for the version number information.

**Comment by Rod-Persky** [comment]
Ian,

the following will get the version - sorry I couldn't get it working last night. 

``` makefile
VERSION=$(shell cat version.h | grep -e [0-9\.]* -o)
EXECUTABLE=$(BASENAME).$(VERSION)
```

@jowr I'll rewrite it to the Modelica format

**Comment by Rod-Persky** [comment]
More in the style of the Modelica makefile, there are a few options that may come in handy such as DEBUG=debug and LIBTYPE=[so,a]. Not quite finished, but it's building just fine.

https://gist.github.com/Rod-Persky/6828026
