### ISSUE TITLE
Unit problems when fitting incompressible liquids

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#62]
I have fit preliminary properties for Dynalene HC-10 HC-20 HC-30 HC-40 HC-50, but there remain some problems in the curve fitting code.

I set the values in fit_incompressible.py to be consistent with the other fluids and the documentation and then changed the fluid that is imported in fit_incompressible.py to HC10 for instance.  The figures are not generated properly, and the units of the coefficient seem to be off by a factor of a 1000 for some odd reason.

Am I missing a units flag somewhere?

Ian

**Comment by jowr** [comment]
I can see you fixed things in the code, great. 

The problem is that I wrote the fitting functions before we changed everything to SI units. Hence, the fitting works in kJ/kg/K and so on. When we changed the units set, I updated the coefficient in the C++ file, but not the fitting procedures. Well, I guess we should do that soon.

I will have a look at the graphs, they should be working no matter what.

**Comment by ibell** [comment]
Except for the viscosity, which is giving some crazy values, and its not a
linear fit so I think I can't just multiply the constants by factors of
1000 ?

**Comment by ibell** [comment]
@jowr, can you fix the viscosities for the Dynalene fluids?  You know the
ins and outs of the incompressible code better than I do

**Comment by jowr** [comment]
I cannot see why you have problems with either plots or viscosity. I made the fits and updated the documentation.
