### ISSUE TITLE
Better solution for gitrevision.h

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#84]
Hey @jowr , I am getting really annoyed with my solution for getting the git revision into the C++ code, as every time I pull your code and you have rebuilt the python wrapper, there is a conflict with the gitrevision.h .  Do you have a better idea of how we can deal with this?  We need to be able to handle the case that the code is not being build from a git repo, or that git is not available, as well as the case that git is available.  I'm just not sure there is a better solution than the status quo.

_Argh_!

**Comment by jowr** [comment]
Hehe, I can understand. My solution is to write a custom merge driver for `gitrevision.h`. You can locally edit your configuration file, which lives in `.git/config` to contain instructions on how to handle conflicts. Add this to `.git/config`:

```
[merge "keepOurs"]
    name = custom merge driver keep the local version
    driver = true
[merge "keepTheirs"]
    name = custom merge driver keep the remote version
    driver = cp -f %B %A
```

I guess the names explain what is going on. Afterwards you have to tell git which of the above drivers should be used for your `gitrevision.h` file. Use the file `.gitattributes`, create if necessary, and add this line:

```
CoolProp/gitrevision.h merge=keepTheirs
```

This will always overwrite the local version. However, if you build the Python wrapper again and commit your changes, you update the remote version of `gitrevision.h`.

Depending on your operating system, you might have to change `cp -f %B %A` to, for example, `cp %B %A`.

**Comment by jowr** [comment]
Just a small update: I committed `.gitattributes`, so there is no need to create that file. Furthermore I just realised that the configuration files have another path on Windows. Instead of `.git/config` you might want to try `C:\Users\username\.gitconfig`. 

The workflow for automatically ignoring changes to `gitrevision.h` is as follows: 
1. Commit all your local changes including `gitrevision.h`
2. Merge/Pull the changes from the remote repository, note that `gitrevision.h` gets treated automatically.
3. Commit the merged files.

The only drawback is that `gitrevision.h` gets updated less frequently since it will only be updated if no newer version exists in the repository. In case that is a problem, you can always change `CoolProp/gitrevision.h merge=keepTheirs` to `CoolProp/gitrevision.h merge=keepOurs`. However, even this strategy will lead to delay of at least one commit questioning the whole purpose of `gitrevision.h`...

**Comment by jowr** [comment]
Ian, did this solve your issues? Can we close this post?

**Comment by ibell** [comment]
Ok, yes I think we can close this.  How did you figure out that info about
the merging?
