### ISSUE TITLE
EES-CoolProp wrapper fails for certain supercritical inputs with R1233ZD

### ISSUE THREAD

**Issue by squoilin** [ibell/coolprop#93]

**Comment by ibell** [comment]
Unfortunately this is a known issue with no clear solution.  It seems like another magical problem with EES, since the same inputs that fail in EES work fine in Python, Excel, C++, etc.  I am trying to work through this problem with EES developers, but have neither a clear resolution, nor a timeline for getting this fixed.

For example, this fails:

```
h_ex_pp_s = coolpropsi('H', 'R1233zde','S',0.07522*1000,'P',4000000)
```

FYI it also fails if we just use coolprop() without the coolpropsi() wrapper.

**Comment by ibell** [comment]
Ugh. _Mea culpa_

**Comment by ibell** [comment]
Was checking based on temp not pressure.  Seems resolved.
